name: Test legacy node version

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build and validate
      run: yarn build
      env:
        WEB3_PROVIDER_URLS_BY_CHAINID: ${{ secrets.WEB3_PROVIDER_URLS_BY_CHAINID }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    - name: Run tests
      run: yarn test
      env:
        WEB3_PROVIDER_URLS_BY_CHAINID: ${{ secrets.WEB3_PROVIDER_URLS_BY_CHAINID }}
        ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        CI_THREAD: "0"